# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     #- run: |
     #echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    # docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t gaurav1der/macaddr:latest .

     # deploy the image
    # - run: docker push company/app:$CIRCLE_BRANCH
