# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
 build:
   docker:
     - image: circleci/golang:1.9
     - image: docker:stable-git
   environment:
     ANCHORE_VERSION: v0.6.1
   steps:
     - checkout
     - setup_remote_docker:
          docker_layer_caching: false
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     #- run: |
     #echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    # docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t gagoel/macaddr:latest .

     # deploy the image
    # - run: docker push company/app:$CIRCLE_BRANCH
